### ISSUE TITLE
Info dialog's "Latest commit" field is never filled

### ISSUE THREAD

**Issue by nekohayo** [flattool/warehouse#100]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

Follow-up to #90:

With my `--user` installation,  
Warehouse's GUI never shows the latest available commit ID, even if you downgraded a package:

![image](https://github.com/flattool/warehouse/assets/479401/6cde6f5d-1679-40a6-a671-aaa1ca15c8bf)

**Comment by heliguy4599** [comment]
Forgive me for the delay in response.

I'm not sure if this information is ever actually available. Perhaps I'm missing something obvious but after looking around in Flatpak, I haven't been able to find when the `Latest Commit` is actually set to something. Perhaps this field should be hidden from the GUI.

If you know any more info about this please let me know.

**Comment by heliguy4599** [comment]
Alrighty, this has been addressed in the newest release by using Flatpak Info for the properties window!

**Comment by nekohayo** [comment]
Out of curiosity, I used Warehouse 1.6.0 to downgrade a random app, and shows up  like this in all situations, with a "Commit" and "Parent" commit field, but no "Latest commit" field:

![image](https://github.com/flattool/warehouse/assets/479401/a3526529-0582-4812-b5f2-cf7048b03c8f)

Was the notion of "Latest" replaced by something else? It's a bit unclear to me.

**Comment by heliguy4599** [comment]
Flatpak doesn't really expose the latest commit in the list or in the info commands. The only way I'd be able to fully provide the latest commit info here is by doing the commit fetches that is done in the downgrade window. That takes a while to do and would mean that the Properties window would have a little spinner on a hypothetical "Latest Commit" row entry.
