### ISSUE TITLE
Downgrade broken (again?)

### ISSUE THREAD

**Issue by VortexAcherontic** [flattool/warehouse#104]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse (1.5.1)
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic
- [x] I have found a closed issue which should be in the latest release: #90 
  - At least it is listed explicitly in the update notes.

## Describe the issue in detail
- Opening the downgrade dialog will show a "Fetching Releases" message and then will show an empty list.
![grafik](https://github.com/flattool/warehouse/assets/11244092/da58e6f0-6b29-4621-969d-a4a635778917)
- I tired this with apps where I did not disabled Updates which show the same errors in the terminal.

## If applicable, provide steps to reproduce the issue
- Try to downgrade app

## Run `flatpak run io.github.flattool.Warehouse` in a terminal and if applicable, show any output

```
Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/downgrade_window.py", line 114, in <lambda>
    task.run_in_thread(lambda *_: self.get_commits())
                                  ^^^^^^^^^^^^^^^^^^
  File "/app/share/warehouse/flattool_gui/downgrade_window.py", line 76, in get_commits
    self.versions.append([commits[i], changes[i], dates[i]])
                                      ~~~~~~~^^^
IndexError: list index out of range
```

**Comment by heliguy4599** [comment]
Hello!
Can you tell me at what one of the apps you were trying to downgrade was? Also could you tell me the output of `flatpak --version`?

**Comment by VortexAcherontic** [comment]
Sure thing can do.

```
flatpak --version
Flatpak 1.15.6
```

So far I tried to rollback OBS Studio and 0 A.D.  
Just now I also tied Armagetron Advanced, Audacity, Warehouse itself and ProtonUp-Qt. All show the same error in the logs. Which leads me to the conclusion it is not working for all my flats.

**Comment by heliguy4599** [comment]
Hello.
Sorry, I haven't been able to recreate this, even with the same version of Flatpak, and with the same apps. I don't have many ideas as to why this would be happening. What distro are you on? I tried it on Arch because Arch has Flatpak 1.15.

**Comment by VortexAcherontic** [comment]
How to some run the app from source?
What I did to look into it myself was:

```
meson setup builddir && cd builddir
meson compile
./src/warehouse 
Traceback (most recent call last):
  File "/opt/datalake/vortex/develop/warehouse/builddir/./src/warehouse", line 42, in <module>
    resource = Gio.Resource.load(os.path.join(pkgdatadir, 'warehouse.gresource'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/local/share/warehouse/warehouse.gresource”: open() failed: No such file or directory (4)
```

How do I overwrite the gressource path to the one next to the executable eg. how to test this app locally?

> What distro are you on?

openSUSE Aeon (based on openSUSE Tumbleweed)

**Comment by VortexAcherontic** [comment]
Did a quick test in a VM with a basic setup so I do not have any fancy additional flatpak repos or maybe some customization I have possibly made which could interfere with this. But also there I a getting the exact same issue (openSUSE Kalpa, also based on openSUSE Tumlbeweed)

**Comment by heliguy4599** [comment]
I have done these similar tests myself and for the life of me I cannot get this bug to appear, I really have no clue. I've tried different virtual machines of the OSes listed and no such errors. I'll have to talk with more people and come at this from a different angle...

**Comment by VortexAcherontic** [comment]
> I have done these similar tests myself and for the life of me I cannot get this bug to appear, I really have no clue. I've tried different virtual machines of the OSes listed and no such errors. I'll have to talk with more people and come at this from a different angle...

Many thanks for looking into it. I myself will do more testing and try different things until I found a working configuration 😅 If I do I will report back asap.

Sorry for reporting this rather frustrating issue.

**Comment by VortexAcherontic** [comment]
OMG you won't fck believe me. I just set my openSUSE Kalpa VM from German to English and guess what .. it works now ... HOW can this be a local issue? o.O

**Comment by heliguy4599** [comment]
Wow you cam to the same possible answer just as Axtlos, a friend, did. Can you go to [this GitHub Action](https://github.com/flattool/warehouse/actions/runs/8460680320) and download the Flatpak file there, install it, and see if the bug is fixed? You'll also need to have 'org.gnome.Platform/x86_64/46' installed as I've upgraded to Libadwaita 1.5

It contains an attempted fix for this by doing exactly what you said: prepending "LC_ALL=C" to the called command.

**Comment by VortexAcherontic** [comment]
How do I get the github action build to use locales as it seems to come without?

**Comment by heliguy4599** [comment]
I'm sorry I do not know how. But, the shell command being ran should be agnostic to the localization of the app, as it's being ran on the host. So as long as your OS itself is set to the locale, you should be able to test this just fine I think.

**Comment by VortexAcherontic** [comment]
> I'm sorry I do not know how. But, the shell command being ran should be agnostic to the localization of the app, as it's being ran on the host. So as long as your OS itself is set to the locale, you should be able to test this just fine I think.

Ah yes you are right, didn't thought abut it this way. Yeah it works very well. Many thanks ❤️

**Comment by heliguy4599** [comment]
You're welcome, and thanks a bunch!
