### ISSUE TITLE
Feature Request: Padlock icon (or some visual indication) for items with disabled updates

### ISSUE THREAD

**Issue by nekohayo** [flattool/warehouse#118]
- [x] My proposal does not exist in the `PLANNED & NOT PLANNED.md` document
- [x] I have not found any other opened issues on the same feature request
- [x] I believe this fits within Warehouse's scope of Flatpak management

## Describe the feature idea in detail

This is a small quality-of-life usability improvement suggestion.

Sometimes, I will disable updates on a package for whatever reason (ex: some known bug, or me wanting to be sure to test the app thoroughly before upgrading to a major version) so I will "Disable updates" on it. However, it may be months (or even years) before a new release comes out and I want to test it, so I may not remember that I had locked it.

I think it would be good, in the main list view, to show a symbolic padlock icon 🔒 to indicate version-locked status, a bit like there is an icon button for EOL status?

**Comment by heliguy4599** [comment]
Currently in Warehouse the EOL Status button also will tell you if the package has its updates disabled, in the same popup. Is this status not working for you? Or do you think this information should be told separately from EOL Status? I'm open to suggestions.

**Comment by nekohayo** [comment]
Oh, you are right, I had not even noticed because the "Uses EOL runtimes" status is so common that my eye tends to ignore it!

Well, that's a good question.
* At the same time... if a package is version-locked, does it make sense to show the EOL warning? I'd think the lock takes precedence, because if the user locked it, they know it's going to stick frozen in time to an old app version (and therefore it is assumed that the underlying platform is inevitably going to be EOL sometime)...
* There apparently also is the "Auto Removal Disabled" third status for dependencies, too... maybe that one could use the same lock symbol as "Updates disabled", with a more explicit label in the clickable button so the user doesn't wonder why its removal is forbidden? I mean, it could be worth making the distinction between "Updates disabled" and "Auto Removal disabled" a bit clearer with some subtext in those popovers.
