### ISSUE TITLE
Feature request: Application folder

### ISSUE THREAD

**Issue by hericiumvevo** [flattool/warehouse#12]
**Feature Request**

**Description:**
I would very much like to see an option to enable an application folder (/home/user/applications/ by default) where the users would simply put .flatpakref files and those would get installed and uninstalled depending on the contents of the folder (perhaps it could open flattool with a prompt how to deal with uninstalling it? or maybe a popup in the panel as an extension?) 

**Use Case:**
I believe many macOS users are used to this behaviour, as well as it being a genuinely useful function.

**Additional Information:**
@axtlos has a similiar projects

**Implementation Suggestions:**
This could be achieved with some sort of a filesystem watcher (check @axtlos's project for more details)

**Comment by heliguy4599** [comment]
Is this something that can be done from a flatpak app or would this be better suited as another project altogether? I'm feeling the latter. It's an interesting idea but I'm not sure if this is a direction in which I want Flattool to head in.

**Comment by hericiumvevo** [comment]
I think it would be best to start it as a project in this org as I imagine it would be heavilty tied to the main apps.
Also if you make it with python I would love to help develop it :D

**Comment by heliguy4599** [comment]
I might work on this project in the future, but it would be under a different app, thus I am closing this feature request. Thanks for the idea!
