### ISSUE TITLE
ugly layout of flatpak property window

### ISSUE THREAD

**Issue by Lanchon** [flattool/warehouse#129]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail

layout of flatpak property window is plain ugly. this happens for example with `org.freedesktop.Platform.VAAPI.Intel`, that has a long name without spaces:

![image](https://github.com/user-attachments/assets/a3b76ba1-ba7c-4c2d-b826-a54d0193c2a1)

compounded with the problem, is that the properties window does not allow resizing or maximizing. for sure i would prefer it to be a fully free window.

thanks!

**Comment by heliguy4599** [comment]
Thanks for bringing this up to me. I have fixed the issue with the UI going out of frame, but I will be keeping the window as this constrained popup. However, in 2.0 the Properties Window will instead be a pane of a split screen, allowing it to take up more room, so look forward to that!

**Comment by Lanchon** [comment]
thank you !!!
