### ISSUE TITLE
Screen stuck on "Loading Flatpaks". Flatpak with more than one line in Description.

### ISSUE THREAD

**Issue by iacques** [flattool/warehouse#130]
After install and run "runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/24.08" the screen stuck on "Loading Flatpaks".

The error:

Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/window.py", line 940, in <lambda>
    lambda *_: GLib.idle_add(lambda *_: self.generate_list_of_flatpaks())
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/warehouse/flattool_gui/window.py", line 328, in generate_list_of_flatpaks
    self.host_flatpaks = self.my_utils.get_host_flatpaks()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/warehouse/flattool_gui/common.py", line 190, in get_host_flatpaks
    data[i].append(lines[i])
                   ~~~~~^^^
IndexError: list index out of range

The column "Description" of this flatpak "ffmpeg-full/x86_64/24.08", returned after  "--columns=all" parameter, have and add three new lines that is not trated in function commom.py (get_host_flatpaks,   lines = output.strip().split("\n") ):

commom.py
...
        output = subprocess.run(
            ["flatpak-spawn", "--host", "flatpak", "list", "--columns=all"],
            capture_output=True,
            text=True,
            env=self.new_env,
        ).stdout
        lines = output.strip().split("\n")
        columns = lines[0].split("\t")
        data = [columns]
        for line in lines[1:]:
            row = line.split("\t")
            data.append(row)

        output = subprocess.run(
            ["flatpak-spawn", "--host", "flatpak", "list", "--columns=runtime"],
            capture_output=True,
            text=True,
            env=self.new_env,
        ).stdout
        lines = output.split("\n")
        for i in range(len(data)):
            data[i].append(lines[i])
        sorted_array = sorted(data, key=lambda item: item[0].lower())
        return sorted_array
...

At uninstall the flatpak ffmpeg-full/x86_64/24.08 the error is gone.

Jacques

**Comment by heliguy4599** [comment]
Thank you! I've been seeing a few reports here and there of this issue but I could never figure out the reason, nor reproduce it. Your information has been greatly valuable and I will work to resolve this right away!

**Comment by heliguy4599** [comment]
Alright folks, I've fixed the issue, it'll be out in a new update very soon. Thanks again for the helpful information in this report that finally allowed me to understand what the problem actually was.
