### ISSUE TITLE
Typo in item title in Runtime screen

### ISSUE THREAD

**Issue by bl8** [flattool/warehouse#151]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail

When view the information for a runtime, the text for one of the items has a typo:
Disable Automactic Removal
should be:
Disable Automatic Removal

See https://github.com/flattool/warehouse/blob/2fd24f3399e3655f7ff984e37b712acaf4b2a05b/src/properties_page/properties_page.blp#L188

**Comment by heliguy4599** [comment]
Thank you for spotting that! This has now been fixed in main.
