### ISSUE TITLE
Merge `Flatseal` and `Warehouse` features into one application

### ISSUE THREAD

**Issue by ovari** [flattool/warehouse#153]
Please merge `Flatseal` and `Warehouse` features into one application.

### Flatseal

https://github.com/tchx84/Flatseal/

https://flathub.org/apps/com.github.tchx84.Flatseal

### Warehouse

https://github.com/flattool/warehouse

https://flathub.org/apps/io.github.flattool.Warehouse

https://www.linuxfordevices.com/tutorials/linux/install-setup-warehouse-flatpak

What do you think?

Thank you

https://github.com/tchx84/Flatseal/issues/737

**Comment by heliguy4599** [comment]
The feature request template (which was not followed) asks you to read the [PLANNED & NOT PLANNED.md](https://github.com/flattool/warehouse/blob/main/PLANNED%20%26%20NOT%20PLANNED.md) file, in which you'll find "Permission management" listed under "Features that will never be added to Warehouse".
