### ISSUE TITLE
user installed flatpaks version rollback uses superuser privileges

### ISSUE THREAD

**Issue by renner0e** [flattool/warehouse#156]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail
user installed flatpaks version rollback feature uses superuser privileges when they don't need to

## If applicable, provide steps to reproduce the issue
I have flathub as a system remote (I don't use it for that particular app) and as a user remote
1. install a flatpak with --user
2. choose app and select the release you want to downgrade to
3. click change version
4. polkit window pops up asking for superuser permissions

`the flatpak update --commit=<id> com.example.app `command works

## Run `flatpak run io.github.flattool.Warehouse` in a terminal and if applicable, show any output

```
Warehouse - Manage all things Flatpak

          ID: io.github.flattool.Warehouse
         Ref: app/io.github.flattool.Warehouse/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.0.0
     License: GPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1,2 MB
     Runtime: org.gnome.Platform/x86_64/47
         Sdk: org.gnome.Sdk/x86_64/47

      Commit: afe75848b144353bb09bcf2958631e576d594684a7898f0475c7cbd3c3736640
      Parent: 15acd48672f73f80306d387c361651f672ca19afc9f048ee2317451e282068b5
     Subject: Update io.github.flattool.Warehouse.json (39a948c2)
        Date: 2024-10-28 05:08:13 +0000

```

**Comment by heliguy4599** [comment]
I see! This was an oversight on my end, sorry! This will be fixed in the next version

**Comment by renner0e** [comment]
thanks!
