### ISSUE TITLE
"Blue" overlay bug when dragging-dropping .flatpakref files to the UI

### ISSUE THREAD

**Issue by brotenet** [flattool/warehouse#157]
- [ x] I have read the `README.md` document
- [x ] I am using the latest version of Warehouse
- [ x] I am using the Flatpak package of Warehouse
- [ x] I have not found any other opened issues on the same topic

## Describe the issue in detail
When dragging and dropping a .flatpakref onto the Warehouse window and the UI "blue" overlay comes up, it does not go away after dropping the .flatpakref file.
The package installation works OK. The installation progress is visible (since the overlay is semi-transparent), all UI controls work even with the overlay visible on top of them (including the window-close button) but the overlay stays there.
The application needs to be closed in order for the overlay to go away.

_Suggestion: The "blue" overlay is not really needed. It could be removed altogether without causing any issues regarding usability because we already have a pop-up dialog showing right after a file is dropped on to the UI._ 

(please see attached video)

https://github.com/user-attachments/assets/9f0d704b-ff20-45f2-a84e-67f758b0f417

## If applicable, provide steps to reproduce the issue
This issue is apparent in Linux Mint (Cinnamon). To reproduce drag and drop a .flatpakref on to the Warehouse UI.

## Run `flatpak run io.github.flattool.Warehouse` in a terminal and if applicable, show any output
No relevant output is shown in the terminal.

**Comment by heliguy4599** [comment]
Thanks for bringing this to my attention! This should be fixed in the next update
