### ISSUE TITLE
Warehouse opens with Remotes highlighted but displaying Packages instead

### ISSUE THREAD

**Issue by Sunspark-007** [flattool/warehouse#160]
- [x ] I have read the `README.md` document
- [x ] I am using the latest version of Warehouse
- [x ] I am using the Flatpak package of Warehouse
- [x ] I have not found any other opened issues on the same topic

## Describe the issue in detail
Loading flatpak warehouse in maximized mode, the sidebar highlights "remotes" but the screen is displaying packages not remotes.

If it going to default to remotes (it shouldn't) then it should display the remotes panel.. to do that currently, you have to click on something else, then back to remotes before it displays the remotes panel.

**Comment by heliguy4599** [comment]
Ah yes, this issue. I've noticed it too and it should be fixed in the next update. Warehouse should open to the last page you used, but the row for the next page gets activated. I believe the issue was because of how the sidebar was being displayed on launch.
