### ISSUE TITLE
Feature request: Ability to install new Flatpak apps

### ISSUE THREAD

**Issue by AsciiWolf** [flattool/warehouse#20]
Warehouse is a great app, however it would be even more useful if it could install new Flatpak apps (either directly from existing remote or at least *.flatpakref files from Flathub or other places). It would be really helpful on Linux distributions such as Ubuntu that do not support Flatpak installation using GUI. :-)

**Comment by heliguy4599** [comment]
Thank you for the complements! I've been asked this by a few other people as well. The goal of Warehouse is to manage what is currently on your system, but I can certainly look into something like this for the future. One thing to note is I do not plan on turning Warehouse into a full on flatpak package manager as that would be beyond my scope of knowledge, but I can work with something more barebones like a direct install of an app ID query.

**Comment by AsciiWolf** [comment]
Nice! The ability to install *.flatpakref files would also be great if it is possible to implement. :-)

**Comment by gregorni** [comment]
I'm wondering, isn't installing apps more of a task that should be handled by a dedicated software center? I can see why it would make sense with `.flatpakref` files, but letting users install apps from a remote seems like it would just be duplicating efforts.

**Comment by AsciiWolf** [comment]
Other parts of this app could also be considered as "duplicating efforts". Anyway, as I mentioned in my original comment, there are many Linux distributions that do not support graphical Flatpak installation via their GUI software centers. Having an app that could be used for basic Flatpak apps management on such distributions would be great.

**Comment by gregorni** [comment]
On most other distros, you can also install software centers that do handle Flatpaks properly, like GNOME Software, so it is possible to have a pleasant Flatpak experience on those distros as well.

About duplicating efforts: I feel like it's okay for the existing parts to just do something that's already possible on another app, because the way Warehouse does it is just better. But installing Flatpaks from a remote is something that I don't see it overtaking GNOME Software at. Latest when it comes to browsing apps, it won't be worth it to try to replicate what GNOME Software already does.

**Comment by AtiusAmy** [comment]
> On most other distros, you can also install software centers that do handle Flatpaks properly, like GNOME Software, so it is possible to have a pleasant Flatpak experience on those distros as well.
> 
> About duplicating efforts: I feel like it's okay for the existing parts to do something that's already possible on another app, because the way Warehouse does it is just better. But installing Flatpaks from a remote is something that I don't see it overtaking GNOME Software at. Latest when it comes to browsing apps, it won't be worth it to try to replicate what GNOME Software already does.

One thing GNOME software can benefit from is the ability to choose between user and system, maybe we can have that in Warehouse, I'm not sure

**Comment by AsciiWolf** [comment]
> On most other distros, you can also install software centers that do handle Flatpaks properly, like GNOME Software, so it is possible to have a pleasant Flatpak experience on those distros as well.

Sadly, this is not true. There are still many distributions that do not support GUI installation of Flatpak apps or even do not support it intentionally (Ubuntu). Having a simple, lightweight app that itself is packaged as a Flatpak and allows basic Flatpak apps management (including their installation) would be a big win for many users of these distributions.

**Comment by heliguy4599** [comment]
I'm at least planning to be able to install ref files and I have searching and installing aPP IDs as an idea on the back burner too. But I would like to say that you can indeed install GNOME Software on Ubuntu and install flatpaks with it that way.

**Comment by AtiusAmy** [comment]
^ yeah 

I think a usecase that would be useful is for installing it in a specific user because GNOME software doesn't support that

**Comment by emanuelserpa** [comment]
I would really like something to install directly with an extension like [Flatline]( https://addons.mozilla.org/pt-BR/firefox/addon/flatline-flatpak/.

**Comment by heliguy4599** [comment]
Just wanted to post here too that Warehouse can now install locally downloaded flatpak files either by selecting them in a file picker, or dragging and dropping them into the main list

**Comment by AsciiWolf** [comment]
Nice, great work! :-)

**Comment by krruzic** [comment]
Working on allowing remote installs today

**Comment by heliguy4599** [comment]
Oh? What do you mean specifically? Sounds interesting.

**Comment by AtiusAmy** [comment]
> Oh? What do you mean specifically? Sounds interesting.

I assume remote installs from Flatpakrefs?

**Comment by heliguy4599** [comment]
Well Warehouse already supports adding new remotes via drag and drop, or from a file selector invoked in the Add a Remove window.

**Comment by krruzic** [comment]
sorry confusing terminology lol. I'm working on allowing you to install from the UI, without having to download a flatpakref file. So basically searching available apps on the remotes and then selecting to install them. One issue I'm having because I don't know meson is how can I have a pip package installed during the build?

**Comment by heliguy4599** [comment]
Ah that's ok. And wow that would be really nice to have! I am not entirely sure how to add a Pip package in to the build either but I certainly can look and ask around. You can join our Discord server / Matrix room if you would like direct connection to the people I'm going to ask as well, but of course no pressure to join, and thanks for working on my app!

**Comment by emanuelserpa** [comment]
> sorry confusing terminology lol. I'm working on allowing you to install from the UI, without having to download a flatpakref file. So basically searching available apps on the remotes and then selecting to install them. One issue I'm having because I don't know meson is how can I have a pip package installed during the build?

This is very good, but I think that just the app accepting the "appstream:" link can make it work. You can just click in "Install" in Flathub and Warehouse would be called to install the app.

**Comment by heliguy4599** [comment]
I'm glad to say that I have finally fully completed the idea of this issue! Warehouse has been able to install Flatpaks from files for a bit now, but as of today, in main, I have added the Install From The Web window. New Flatpaks can now be installed from a simple search.

**Comment by AtiusAmy** [comment]
> I'm glad to say that I have finally fully completed the idea of this issue! Warehouse has been able to install Flatpaks from files for a bit now, but as of today, in main, I have added the Install From The Web window. New Flatpaks can now be installed from a simple search.

woah, i cant believe you sai dthat to me... im a sigma,..
