### ISSUE TITLE
Feature request: Remember GUI shape

### ISSUE THREAD

**Issue by signdo** [flattool/warehouse#29]
It's too wide!
Maybe you should consider saving the adjusted shape.

**Comment by heliguy4599** [comment]
I can look into adding this. Currently I do not know how. Out of curiosity, may I ask what screen size / device you are using?

**Comment by signdo** [comment]
1920*1080

You can adjust the size of the window at startup to fit the width of the software list and the number of entries, which will look good.

**Comment by heliguy4599** [comment]
I have just added in a recent commit the ability for the app to remember the main window's size. This will be in the next release (1.1.0) which will come out very soon.
