### ISSUE TITLE
Feature request: Pin / Unpin patterns / runtimes

### ISSUE THREAD

**Issue by Xathros1** [flattool/warehouse#30]
As written above. 

> Flatpak maintains a list of patterns that define which refs are pinned. A pinned ref will never be automatically uninstalled (as are unused runtimes periodically). This can be useful if for example you are using a runtime for development purposes.
> Runtimes that are explicitly installed, rather than installed as a dependency of something else, are automatically pinned.

However, that also means that in order to remove unused pinned patterns u need to get into the terminal to remove them via (example):
```
flatpak --system pin --remove org.freedesktop.Platform//19.08
or
flatpak --user pin --remove org.freedesktop.Platform//19.08

```

**Comment by heliguy4599** [comment]
I am looking in to adding this but currently pinning seems to be very automated by Flatpak. Also, now this could be me just not understanding it properly, but pinning with Flatpak seems a bit erratic in its behavior so I don't fully understand it.

**Comment by Xathros1** [comment]
Yes, the way flatpak handles it is a pain. That's why having the option to unpin those runtimes that get pinned automatically in a easy straightforward way would be awesome.

**Comment by heliguy4599** [comment]
Hello! The next update to warehouse will be able to pin and unpin runtimes. I think custom user made patterns are outside the scope of Warehouse. I'll close this as completed now!
