### ISSUE TITLE
[Issue] Top line needs more padding

### ISSUE THREAD

**Issue by Scotty-Trees** [flattool/warehouse#35]
Greetings, great work and thanks for a super useful app! 

The only issue I have is a UI one that should be a simple fix. But the padding style on the top line is almost nonexistent and needs to be adjusted. I don't know if Gnome HiG has a specific size, but if you look at other Gnome apps, which I'll show below they all have a bit of padding in the top, which in part helps with legibility/readability. I say padding, perhaps it goes by another name, but hopefully the following screenshots below illustrate my point. It'd be nice to fix this so it is more inline with other Gnome apps, thank you!

![Screenshot from 2023-10-06 14-28-06](https://github.com/flattool/warehouse/assets/45135187/a5bfc4be-3c7f-4079-9696-fad8632c2ea1)
![Screenshot from 2023-10-06 14-31-37](https://github.com/flattool/warehouse/assets/45135187/b392407a-7176-4b48-b244-1046a84603ff)
![Screenshot from 2023-10-06 14-34-11](https://github.com/flattool/warehouse/assets/45135187/737333f1-b16d-4a9e-924d-38bc570a5779)
![Screenshot from 2023-10-06 14-40-34](https://github.com/flattool/warehouse/assets/45135187/c348c723-0c94-4a5d-9ea7-d7c7fae5593e)

I'm sure there's more apps that use padding, it just depends, but please let me know if this is something you can adjust, thanks again.

**Comment by heliguy4599** [comment]
How does this look? I'm using here the same spacing amount that I found within GNOME Software.

![image](https://github.com/flattool/warehouse/assets/95997226/71075c4b-4dd1-4456-9fde-d54bd450fe38)

**Comment by Scotty-Trees** [comment]
Yeah I think that looks perfect, I’d be happy with that change for sure 👍

**Comment by heliguy4599** [comment]
Awesome thanks. The change has been added to the recent commits and will ship with the next update, as such, I'll close this. Thanks again!

**Comment by Scotty-Trees** [comment]
Awesome, thank you as well! Your app is extremely value, at least for my workflow, FYI. Instead of having to use the terminal for everything flatpak related, which isn't a bad thing, but it's nice to finally have a GUI option that allows Gnome/GTK users to quickly and easily adjust flatpaks. I look forward to using this when Fedora 39/Gnome 45 lands. Cheers!

**Comment by heliguy4599** [comment]
That's really awesome to here. Thank you so much for the kind words and I'm super happy to hear that this app is helping you out! :+1:
