### ISSUE TITLE
Feature Request: Sort by name instead of app ID

### ISSUE THREAD

**Issue by jakedane** [flattool/warehouse#38]
Currently Warehouse sorts apps by their app ID. That's the same as `flatpak list` does but I think it makes for a jumbled reading because app names are not in alphabetical order:

![image](https://github.com/flattool/warehouse/assets/114460917/dd01399f-3da2-4b1f-bd80-ac72ba53ab4a)

I think the list would be easier to navigate if it were sorted by app name, same as Flatseal does for example. I realize I can search for app names but I don't know which all apps I have installed. If the default won't be changed to sort by name, could it be a filter option or preference?

**Comment by heliguy4599** [comment]
I will look into how I can make this change. Thanks for bringing your concerns to my attention. :+1:

**Comment by heliguy4599** [comment]
Alright this has been added in the recent commits and will be in the next update, as such I am closing this issue. Thanks for the recommendation!
