### ISSUE TITLE
App remotes duplicates when you have a remote of different name

### ISSUE THREAD

**Issue by AtiusAmy** [flattool/warehouse#39]
![image](https://github.com/flattool/warehouse/assets/136548767/c82db5a7-673e-4138-8d20-3176a7a51f44)
I have the elementary remote right here (I installed from elementary flatpakref)

However once I go into adding new remotes 
![image](https://github.com/flattool/warehouse/assets/136548767/f7e83828-a4c6-4ed2-94a0-53046725f8bd)
the elementary remote is still here despite me already adding it

Maybe the detection should be changed to remote link?

**Comment by heliguy4599** [comment]
Hmm I can't seem to replicate this behavior

**Comment by AtiusAmy** [comment]
Try adding remotes with the same link but different names :P

**Comment by heliguy4599** [comment]
Alrighty, I've fixed this in the latest commit, and the fix will be in the next update. Thank you.
