### ISSUE TITLE
Feature request: In runtime view show apps using selected runtime

### ISSUE THREAD

**Issue by pktiuk** [flattool/warehouse#42]
In the window showing info about selected runtime there should be also a list of apps which use that runtime.

**Comment by heliguy4599** [comment]
This is something that I could maybe add, but what I'm working on currently is the ability to filter apps and runtimes by what runtimes are selected. And that would be part of the filters window.

**Comment by heliguy4599** [comment]
Alright I have added both the ability to filter by selected runtimes as well as added a filter button in the properties window of runtimes which will set a filter specifically to itself. This accomplishes exactly what you've asked for and has been added in the latest commits. As such I will close this issue. Thanks for the interest and the feature idea!
