### ISSUE TITLE
merge with flatseal?

### ISSUE THREAD

**Issue by vhdirk** [flattool/warehouse#43]
I think it'd be pretty great if warehouse and @tchx84's https://github.com/tchx84/flatseal would merge to become the one-stop-shop for flatpak management. 

I am well aware that projects like this are voluntary projects, for example as a hobby in spare time, where you may just want to do your own thing.

But still, I think these 2 combined would be very useful indeed!

**Comment by heliguy4599** [comment]
Thanks for your interest in my project, but a merging of these two apps is something that would take a monumental amount of effort and time that I sadly just do not have. Not to mention that I don't even know if that's the direction Flatseal wants to go in.
