### ISSUE TITLE
Feature request: Implement flathub.org verification

### ISSUE THREAD

**Issue by loganmarchione** [flattool/warehouse#48]
I would appreciate it if you implemented [flathub.org verification](https://flathub.org/apps/collection/verified/1) (so that users know that builds from GitHub are actually what end up on Flathub.org). I believe if you login to Flathub.org, there are instructions in your developer profile.

**Comment by heliguy4599** [comment]
I would love to do that, but there exists an issue with the flathub website that prevents me from verifying. I've reported it to the website maintainers and they tell me there is a fix on the way, but it could take a while to be implemented.

**Comment by loganmarchione** [comment]
Just [linking](https://github.com/flathub/website/issues/2035) to the issue so I can track it myself. Thanks for the info!
