### ISSUE TITLE
Feature request: add "flatpak" to search keywords list

### ISSUE THREAD

**Issue by Vovkiv** [flattool/warehouse#52]
"Warehouse" is not name that someone can easily remember, so I suggest to add "flatpak" keyword to https://github.com/flattool/warehouse/blob/main/data/io.github.flattool.Warehouse.desktop.in as "Keywords=flatpak;", so when you would search for this app in your apps list, you can just type "flat".

**Comment by heliguy4599** [comment]
Thanks to runarcn's merge in #54, this has been added to the recent commits and will be in the next update! As such I'm closing this issue and thanks for the idea!

**Comment by Vovkiv** [comment]
Yay, thanks!
