### ISSUE TITLE
feature request: launch apps from Warehouse

### ISSUE THREAD

**Issue by Rexogamer** [flattool/warehouse#53]
Heya!

A feature I think would be useful (and probably not too cumbersome) would be the ability to launch an app directly.

Love the app, both in terms of looks and functionality ^^

**Comment by heliguy4599** [comment]
Thanks so much for the compliments! The ability to launch apps has been added in the recent commits and will be part of the next feature release. Unfortunately I have no release date or ballpark to give you for that sorry, but just know that it will be in there! As such, I'll close this issue as completed. Thanks again!
