### ISSUE TITLE
Incorrect comment

### ISSUE THREAD

**Issue by PopoutApps** [flattool/warehouse#55]
Warehouse falsely stated "This application is no longer maintained." (or something very similar) for an application which had been updated only 5 months previously. That was presumably because it was using a just out-of-date Flatpak platform. Flathub simply and accurately stated that it was using an out-of-date platform.

**Comment by heliguy4599** [comment]
May I see a screenshot of this? I've yet to experience such so I would really like to see exactly what part of the UI has this false warning.

**Comment by heliguy4599** [comment]
Can you provide the name of the app that had this issue in Warehouse?

**Comment by PopoutApps** [comment]
Sorry, too late. I've updated the Flatpak platform of may app so that it won't appear. I'm guessing it appears on the front panel as an error in red text, or when you click on the "i" icon next to that error. See Easydict-GTK or Handbrake which say "Runtime EOL".
   On Monday, 23 October 2023 at 04:35:46 BST, heliguy4599 ***@***.***> wrote:  
 
 


Can you provide the name of the app that had this issue in Warehouse?
