### ISSUE TITLE
Two Flathub Beta Remote 

### ISSUE THREAD

**Issue by Raul1198** [flattool/warehouse#61]
- [Y] I have read the README
- [Y] I am using the latest version of Warehouse
- [Y] I am using the Flatpak package of Warehouse
- [Y] I have not found any other opened issues on the same topic

## Describe the issue in detail
after adding flathub beta remote either as user or system when i go to gnome software and search for OBS Studio there in the application page there were two flathub beta option in the drop down menu and both beta  show two different versions of software , on one flathub beta i am getting version 30.0.0 and another showing 29.1.0(which is older than current stable which is version 29.1.3)
[Screencast from 2023-10-24 18-08-17.webm](https://github.com/flattool/warehouse/assets/29801315/44f8b72b-df15-407e-8186-418b2fba0f87)

 
## If applicable, provide steps to reproduce the issue
add the flathub beta remote from hamburger menu in Warehouse then open gnome software and search or obs and change source from the drop down menu

**Comment by heliguy4599** [comment]
I've replicated the steps above and even more strangely, I get no Flathub Beta dropdowns in GNOME Software for OBS at all. It only shows me regular Flathub and the system repo. I will continue looking into the issue but in the mean time, can you tell me if this issue happens for just OBS, or do other apps also have duplicated Flathub Beta dropdowns? Thanks for your report.

**Comment by kra-mo** [comment]
This is not a Warehouse issue. Not sure if it is even an issue at all or just a quirk of Flathub Beta.
