### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by julianfairfax** [flattool/warehouse#64]
The window is a bit too wide to be used on mobile screens. It also doesn't declare itself as supporting mobile devices, so it doesn't show on mobile home screens. Otherwise, it works great on those devices. This issue is to address the two issues.

**Comment by heliguy4599** [comment]
I test my app on a Pixel 3a, and my friend on her One plus 6 and the app seems to fit on those so this is news to me. May I see a screenshot of the app on your phone? As for the mobile device support, I've done all I believe I can in the metadata to say that I support mobile devices, but I've been told that that status seems to not be reported for any Flathub app. Not sure why.

**Comment by julianfairfax** [comment]
Sorry, the screen size is actually fine (I had confused it with another app). As for reporting it as supporting mobile devices, adding `X-Purism-FormFactor=Workstation;Mobile;` to the app's desktop file should work.

**Comment by heliguy4599** [comment]
Alright, I have just added that line in the desktop file and that will be included in the next update. Thanks!
