### ISSUE TITLE
Big Black borders around Window when "direct graphic rendering" is enabled

### ISSUE THREAD

**Issue by firefoxlover** [flattool/warehouse#65]
- [x] I have read the README
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail
The app has huge black barriers when run in a KDE Wayland session with "direct graphics rendering" enabled.

![Screenshot](https://gitlab.gnome.org/GNOME/gtk/uploads/7c2df366f188d126ba13a11731af2bc3/warehouse-shadow-bug.png)

## If applicable, provide steps to reproduce the issue
Install the Flatpak on a Fedora Kinoite KDE Wayland system

## Run `flatpak run io.github.flattool.Warehouse` in a terminal and if applicable, show any output

(with direct graphic rendering disabled)
```
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (Datei oder Verzeichnis nicht gefunden)
```

with direct graphic rendering enabled the second warning doesnt show, but the black borders are there

**Comment by firefoxlover** [comment]
[GTK issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/6192)

**Comment by heliguy4599** [comment]
As firefoxlover pointed out, this is an issue with GTK.
