### ISSUE TITLE
What GTK version is used?

### ISSUE THREAD

**Issue by firefoxlover** [flattool/warehouse#66]
I am in the Gnome Gitlab right now, as this app was the only one with a [weird graphical bug with black borders around the window](https://gitlab.gnome.org/GNOME/gtk/-/issues/6192) which disappeared when disabling direct Graphics rendering.

I dont know how to find out the GTK version used, sorry

**Comment by heliguy4599** [comment]
That's ok no problem. Warehouse currently uses GTK 4 with Libadwaita 1.4

**Comment by heliguy4599** [comment]
Closing this issue now. I left it open in case the original poster wanted to add more on and it seems they don't. Also considering turtlegarden's troubleshooting dialog has been merged, everything brought up here is taken care of. Thanks again

**Comment by firefoxlover** [comment]
no, thanks just wanted to know the version to report the bug to GTK, thanks!
