### ISSUE TITLE
Status page issues

### ISSUE THREAD

**Issue by turtlegarden** [flattool/warehouse#67]
- [x] I have read the README
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail

The search views in Warehouse do not display an `AdwStatusPage` when there are no search results; they simply display an empty `GtkListBox`, which looks slightly jarring.

| Main Window | Orphaned Data Window |
| :----: | :----: |
| ![A Warehouse window showing a weirdly-formatted list box without contents on empty search](https://github.com/flattool/warehouse/assets/52264162/283a9bf8-5e05-489e-96d4-c9daf42873e7) | ![A Warehouse orphaned data window showing a weirdly-formatted list box without contents on empty search](https://github.com/flattool/warehouse/assets/52264162/7477f9d6-f0e0-4dfc-991b-805a6867b51f) |

Other similar apps with search views implement an `AdwStatusPage` with a `loupe-symbolic` icon as per the HIG for search views.

| Jellybean | Workbench | Flatseal |
| :----: | :----: | :----: |
| ![Jellybean showing a status page on empty search ](https://github.com/flattool/warehouse/assets/52264162/10245eff-a9d3-4b41-b7f4-7b67c94b56dd) | ![Workbench's Library showing a status page on empty search](https://github.com/flattool/warehouse/assets/52264162/5cd626d7-cd9a-4816-8cce-48a2b835eb68) | ![Flatseal showing a status page on empty search](https://github.com/flattool/warehouse/assets/52264162/46541d0e-15f4-447e-aefa-e5dd2849d292) |

## If applicable, provide steps to reproduce the issue

- Open Warehouse
- Search for a nonexistent app
- Note the weird formatting

## How can you fix it?

I can help add UI definitions to the `.blp` files to aid with showing a status page when no results are returned, as well as contribute to the Python code (despite me not knowing Python or PYGObject that well).

**Comment by heliguy4599** [comment]
Wow this is really in depth and thought out, plus you looked through the code and wrote some yourself. MASSIVE thank you for all of that work! Let me peruse the PR that I will most likely approve of, and once again, thank you!

**Comment by heliguy4599** [comment]
Issue closed due to MR 69 being merged, thanks again!
