### ISSUE TITLE
Feature Request: nuke all flatpaks and associated data if user has "nor/mal" in bio

### ISSUE THREAD

**Issue by runarcn** [flattool/warehouse#74]
- [ x ] My proposal does not exist in the `PLANNED & NOT PLANNED.md` document
- [ x ] I have not found any other opened issues on the same feature request
- [ x ] I believe this fits within Warehouse's scope of Flatpak management

## Describe the feature idea in detail
if someone has "nor/mal" or other bigoted bullshittery in their bio somewhere, warehouse should automatically nuke all flatpaks and associated data.

## If needed, provide any screenshots, mockups, or other items to help illustrate your point
![image](https://github.com/flattool/warehouse/assets/52424029/e8281e58-a111-4fb9-b93a-53a83230a2af)

**Comment by heliguy4599** [comment]
looking into this...
