### ISSUE TITLE
Folders won't open

### ISSUE THREAD

**Issue by E-D-W-I-N** [flattool/warehouse#89]
Hi, I have a problem with "Open User Data Folder" button. It won't do anything. I've tried launching warehouse from terminal to see if there's any logs but no, it's empty

If I press "Open User Data Folder" button for a few times warehouse shows an error - "Could not open folder"

Is there any permissions what I should enable in Flatseal to actually open that user data folder?

Distro: Arch
WM: Sway

**Comment by E-D-W-I-N** [comment]
UDP:
I managed to get this logs from "Manager leftover data" window. It also has "Open Data Folder" button and it also does nothing

I hope this helps
```
Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/orphans_window.py", line 177, in open_button_handler
    Gio.AppInfo.launch_default_for_uri(f"file://{path}", None)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/orphans_window.py", line 179, in open_button_handler
    properties_toast_overlay.add_toast(Adw.Toast.new(_("Could not open folder")))
    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'properties_toast_overlay' is not defined
```

**Comment by heliguy4599** [comment]
Hi, sorry for the delay in response!
May I ask what file manager you have installed, and what desktop portals you have installed?
And I don't think this is a permissions issue, but good idea.

**Comment by heliguy4599** [comment]
Hi again once sorry for the delay!
I've been able to spin up a vm and get the issue fixed within it by installing:
`libportal-gtk4`
Maybe this will work for you?

**Comment by E-D-W-I-N** [comment]
Sadly, but no, I've tried both `libportal-gtk4` and `libportal-gtk3` and got same error again

```
Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/orphans_window.py", line 177, in open_button_handler
    Gio.AppInfo.launch_default_for_uri(f"file://{path}", None)
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed. (3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/warehouse/flattool_gui/orphans_window.py", line 179, in open_button_handler
    properties_toast_overlay.add_toast(Adw.Toast.new(_("Could not open folder")))
    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'properties_toast_overlay' is not defined
```

**Comment by heliguy4599** [comment]
I hate to just link to somewhere else, but in this case I think I stumbled into something that might be able to help you out in this.
[Manjaro Forum Topic](https://forum.manjaro.org/t/link-in-flatpak-apps-wont-open-on-click-since-anymore-last-update/149907/22)

**Comment by E-D-W-I-N** [comment]
> I hate to just link to somewhere else, but in this case I think I stumbled into something that might be able to help you out in this. [Manjaro Forum Topic](https://forum.manjaro.org/t/link-in-flatpak-apps-wont-open-on-click-since-anymore-last-update/149907/22)


Thanks! This helped me a lot. I checked default app for directory mime with `gio mime inode/directory` and I found what the default app was not my file manager, but my disk usage analyzer tool which just failed to open.

I've changed default handler for inode/directory mime to my file manager and now Warehouse works great!

Once again, thanks :)
