### ISSUE TITLE
Downgrades are broken?

### ISSUE THREAD

**Issue by nekohayo** [flattool/warehouse#90]
- [x] I have read the `README.md` document
- [x] I am using the latest version of Warehouse
- [x] I am using the Flatpak package of Warehouse
- [x] I have not found any other opened issues on the same topic

## Describe the issue in detail

Demonstration video:
[Screencast from 2024-03-04 10-36-51.webm](https://github.com/flattool/warehouse/assets/479401/b4f2113f-948c-4734-a4bc-74e4efad69a9)

## Steps to reproduce the issue

1. `flatpak install --user org.gnome.gitgDevel` with GNOME Nightly version
2. Try to downgrade to a previous version, without "Disable Upgrades"

Result: nothing happens in practice. Both warehouse and flatpak on the commandline confirm that the package has remained at the latest version.

## Terminal output

There was no output in the terminal.

**Comment by nekohayo** [comment]
Furthermore, if you manually downgrade using the commandline, such as:

`flatpak update --user --commit=2c877f18bcdd72bad4d0138625298edb70e90082e76570a1555546a8faa66da3 org.gnome.gitgDevel`

…then warehouse's GUI still does not show the latest available commit ID compared to the one you checked out:

![image](https://github.com/flattool/warehouse/assets/479401/9f85390f-c758-42e2-b5a7-d244a13826a5)

**Comment by heliguy4599** [comment]
I have figured out the issue, the code for downgrades runs with pkexec at all times, even for --user installed applications. This causes the Flatpak to think those --user installed apps are not installed because it's being ran as root. I know how to fix this and it will be resolved shorty. Thanks for bringing this to my attention!

**Comment by nekohayo** [comment]
Seems like the fix was committed and released now!
