### ISSUE TITLE
Feature Request: Commit dates in the app's properties information dialog

### ISSUE THREAD

**Issue by nekohayo** [flattool/warehouse#91]
- [x] My proposal does not exist in the `PLANNED & NOT PLANNED.md` document
- [x] I have not found any other opened issues on the same feature request
- [x] I believe this fits within Warehouse's scope of Flatpak management

## Describe the feature idea in detail

Currently, you can see the commit ID hashes in the properties of an app:

![image](https://github.com/flattool/warehouse/assets/479401/9f85390f-c758-42e2-b5a7-d244a13826a5)

…however, the date and time stamps of those commits are missing, unlike in the Downgrade dialog. It would be convenient to be able to see those dates and times here, whether as a way of confirmation, for troubleshooting, and for knowing how far behind you are on your updates for a particular package.

**Comment by heliguy4599** [comment]
So currently all flatpak info is gotten from `flatpak list --columns=all`, and perhaps that is not the best approach. I think I want to switch to using `flatpak info <ref> --<install type>` as that has more and better detail. It would be a big refactor on how a lot of Warehouse works however so I'm not expecting that to be in a near update.

**Comment by heliguy4599** [comment]
Alrighty, this has been addressed in the newest release by using Flatpak Info for the properties window!
