### ISSUE TITLE
Translations appear broken (empty) in repository and Weblate

### ISSUE THREAD

**Issue by Gert-dev** [flattool/warehouse#94]
Hello

PR #92 was merged yesterday, but it seems to clear several localization files, including [Dutch in `nl.po`](https://github.com/flattool/warehouse/pull/92/files#diff-44a066469e7c75b3cdbbe18743cae1045124dcb86d20c65269ba4c323b04f61c).

Related to this, the Weblate translation page is mostly empty for several languages, such as Dutch.

**Comment by heliguy4599** [comment]
Wow, thank you for bringing this to my attention. I've been having quite a bit of trouble with the translations as of late. I'm currently looking into this and trying to fix it with my Weblate provider.

**Comment by heliguy4599** [comment]
I think we've got it under control. Translations seem to be back in order, with no missing work.
